# Generated by Django 4.1.6 on 2023-02-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositproducts",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="deposits",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="deposits",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
