# Generated by Django 4.1.7 on 2023-02-22 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0005_remove_depositproducts_valid_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deposits",
            old_name="deposit_product_id",
            new_name="deposit_product",
        ),
        migrations.AlterField(
            model_name="depositproducts",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0)]
            ),
        ),
        migrations.AlterField(
            model_name="depositproducts",
            name="max_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)]
            ),
        ),
        migrations.AlterField(
            model_name="depositproducts",
            name="min_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)]
            ),
        ),
        migrations.AlterField(
            model_name="deposits",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)]
            ),
        ),
    ]
